// Generated by CoffeeScript 1.9.3
(function() {
  var activate, clickablePosition, desactivateActive, displayCandidate, displayCandidates, doneForToday, getAccountHtml, getAccountsHtml, getAuthorHtml, handleKeys, initNav, next, prev, updateNav, updatePosition;

  $(function() {
    console.log('starting!');
    $.get('/tomorrow.json').then(displayCandidates).then(initNav).fail(function(err) {
      return console.error(err.stack || err);
    });
    $('#prev').click(prev);
    $('#next').click(next);
    return $(document).keydown(handleKeys);
  });

  displayCandidates = function(data) {
    console.log('data', data);
    data.forEach(displayCandidate);
    return doneForToday();
  };

  doneForToday = function() {
    return $('#authors').append("<div class='candidate done'>done for today!</div>");
  };

  displayCandidate = function(candidate) {
    var accounts, accountsHtml, author, authorHtml, html;
    author = candidate.author, accounts = candidate.accounts;
    authorHtml = getAuthorHtml(author);
    accountsHtml = getAccountsHtml(accounts);
    html = "<div class='candidate'>" + authorHtml + accountsHtml + "</div>";
    return $('#authors').append(html);
  };

  getAuthorHtml = function(author) {
    var authorHtml, description, id, label, picture;
    id = author.id, label = author.label, description = author.description, picture = author.picture;
    authorHtml = "<h2><a href='https://www.wikidata.org/wiki/" + id + "' target='_blank'>" + id + " - " + label + "</a></h2>";
    if (description != null) {
      authorHtml += "<h3>" + description + "</h3>";
    }
    if (typeof extract !== "undefined" && extract !== null) {
      authorHtml += "<p class='extract'>" + extract + "</p>";
    }
    if (picture != null) {
      authorHtml += "<img src='" + picture + "' alt='no picture'>";
    }
    return "<div class='author'>" + authorHtml + "</div>";
  };

  getAccountsHtml = function(accounts) {
    var accountsHtml;
    if (!(accounts.length > 0)) {
      return "<div class='accounts'>no accounts found</div>";
    }
    accountsHtml = accounts.map(getAccountHtml);
    return "<div class='accounts'>" + accountsHtml + "</div>";
  };

  getAccountHtml = function(account) {
    var accountHtml, description, followers_count, lang, location, name, profile_image_url, screen_name, verified;
    profile_image_url = account.profile_image_url, name = account.name, description = account.description, screen_name = account.screen_name, location = account.location, lang = account.lang, followers_count = account.followers_count, verified = account.verified;
    accountHtml = "<img src=\"" + profile_image_url + "\" alt=\"\">\n<h4>" + name + "</h4>\n<a href='https://twitter.com/" + screen_name + "' target='_blank'>" + screen_name + "</a>";
    accountHtml += followers_count > 1000 ? "<p class='over1000'>" : "<p>";
    accountHtml += "<strong>followers:</strong> " + followers_count + "</p>";
    if (description !== '') {
      accountHtml += "<p><strong>description:</strong> " + description + "</p>";
    }
    if (location !== '') {
      accountHtml += "<p><strong>location:</strong> " + location + "</p>";
    }
    if (lang !== '') {
      accountHtml += "<p><strong>lang:</strong> " + lang + "</p>";
    }
    if (verified) {
      accountHtml += "<p class='verified'><strong>verified</strong></p>";
    }
    return "<div class='account'>" + accountHtml + "</div>";
  };

  activate = function($el) {
    return $el.addClass('active');
  };

  desactivateActive = function() {
    return $('.candidate.active').removeClass('active');
  };

  updateNav = function() {
    updatePosition('prev');
    return updatePosition('next');
  };

  updatePosition = function(position) {
    if (clickablePosition(position)) {
      return $("#" + position).show();
    } else {
      return $("#" + position).hide();
    }
  };

  clickablePosition = function(position) {
    return $('.candidate.active')[position]().length === 1;
  };

  initNav = function() {
    activate($('.candidate').first());
    return updateNav();
  };

  prev = function() {
    var $prev;
    if (clickablePosition('prev')) {
      $prev = $('.candidate.active').prev();
      desactivateActive();
      activate($prev);
      return updateNav();
    }
  };

  next = function() {
    var $next;
    if (clickablePosition('next')) {
      $next = $('.candidate.active').next();
      desactivateActive();
      activate($next);
      return updateNav();
    }
  };

  handleKeys = function(e) {
    switch (e.which) {
      case 37:
        return prev();
      case 39:
        return next();
    }
  };

}).call(this);
